### PR TITLE
closes #48 Add hack to detect windows architecture and then abuse the…

### LINKED ISSUE #48: Installation under windows fails because of zlib
luarocks install faketorio ZLIB_DIR=C:\MinGW\msys\1.0\bin ZLIB_INCDIR=C:\MinGW\msys\1.0\include

### PR DESCRIPTION
**Pull request by JonasJurczok**
… zip.exe packed with luarocks

### CODE REVIEW

**Comment by JonasJurczok** [comment]
@Tarrke @hoylemd : can you please take a look at this?
It feels like the only solution for the moment.

Downsides:
- ultra hacky
- only works with the inflated version of luarocks, not with the "all in one exe"

What is your opinion?

File: src/faketorio/package.lua [hunk 1]
```diff
@@ -3,9 +3,21 @@ if not faketorio then faketorio = {} end
...
-    local zip = require("luarocks.tools.zip")
+
+    local cfg = require("luarocks.core.cfg")
 
     assert(faketorio.lfs.chdir("target"))
-    zip.zip(faketorio.output_name .. ".zip", faketorio.output_name)
+    -- ULTRA HACK because installing zlib on windows is a huuuuge pain
+    -- we abuse the laurocks zip exe that gets packed with it. This does not work with the luarocks standalone.exe!
+    if (cfg.arch:find("win32")) then
+        local zip = faketorio.faketorio_path .. "/../../../../tools/7z.exe"
```
Comment (hoylemd) [inline src/faketorio/package.lua]: Doesn't need to be backslashes for windows?
